/* eslint-disable */
/* tslint:disable */
/*
 * ---------------------------------------------------------------
 * ## THIS FILE WAS GENERATED VIA SWAGGER-TYPESCRIPT-API        ##
 * ##                                                           ##
 * ## AUTHOR: acacode                                           ##
 * ## SOURCE: https://github.com/acacode/swagger-typescript-api ##
 * ---------------------------------------------------------------
 */

import {
  CoinPriceDto,
  CreateSwapRQ,
  CreateSwapRS,
  SwapDTO,
  SwapEstimationRS,
  SwapLimitsRS,
  SwapProviderDTO,
  TokenDTO,
} from "./data-contracts";

export namespace Api {
  /**
   * @description Fetches the list of enabled providers with their supported pairs.
   * @tags Swap Providers
   * @name ProvidersControllerGetProviders
   * @request GET:/api/providers
   */
  export namespace ProvidersControllerGetProviders {
    export type RequestParams = {};
    export type RequestQuery = {};
    export type RequestBody = never;
    export type RequestHeaders = {};
    export type ResponseBody = SwapProviderDTO[];
  }
  /**
   * @description Fetches the details of the provider with the given ID if enabled.
   * @tags Swap Providers
   * @name ProvidersControllerGetProviderById
   * @request GET:/api/providers/{id}
   */
  export namespace ProvidersControllerGetProviderById {
    export type RequestParams = {
      /**
       * ID of the provider to fetch
       * @example "MOCK"
       */
      id: string;
    };
    export type RequestQuery = {};
    export type RequestBody = never;
    export type RequestHeaders = {};
    export type ResponseBody = SwapProviderDTO;
  }
  /**
   * @description Returns the estimation for the given amount of each provider that supports that pair
   * @tags Swaps
   * @name SwapsControllerGetSwapEstimation
   * @request GET:/api/swaps/estimate
   */
  export namespace SwapsControllerGetSwapEstimation {
    export type RequestParams = {};
    export type RequestQuery = {
      /**
       * The amount of the origin network to swap, in the smallest unit for that token
       * @format int64
       */
      from_amount: bigint | number;
      /** The token to swap to */
      to_token: string;
      /** The token to swap from */
      from_token: string;
      /** The network to swap to */
      to_network: string;
      /** The network to swap from */
      from_network: string;
    };
    export type RequestBody = never;
    export type RequestHeaders = {};
    export type ResponseBody = SwapEstimationRS[];
  }
  /**
   * @description Returns the overall limits across all providers for the given pair
   * @tags Swaps
   * @name SwapsControllerGetSwapLimits
   * @request GET:/api/swaps/limits
   */
  export namespace SwapsControllerGetSwapLimits {
    export type RequestParams = {};
    export type RequestQuery = {
      /** The token to swap to */
      to_token: string;
      /** The token to swap from */
      from_token: string;
      /** The network to swap to */
      to_network: string;
      /** The network to swap from */
      from_network: string;
    };
    export type RequestBody = never;
    export type RequestHeaders = {};
    export type ResponseBody = SwapLimitsRS;
  }
  /**
   * @description Create a swap on a specific provider
   * @tags Swaps
   * @name SwapsControllerCreateNewSwap
   * @request POST:/api/swaps
   */
  export namespace SwapsControllerCreateNewSwap {
    export type RequestParams = {};
    export type RequestQuery = {};
    export type RequestBody = CreateSwapRQ;
    export type RequestHeaders = {};
    export type ResponseBody = CreateSwapRS;
  }
  /**
   * @description Fetch the information of a swap of a specific provider
   * @tags Swaps
   * @name SwapsControllerGetSwapStatus
   * @request GET:/api/swaps
   */
  export namespace SwapsControllerGetSwapStatus {
    export type RequestParams = {};
    export type RequestQuery = {
      /**
       * ID of the provider of the swap
       * @example "MOCK"
       */
      provider_id: string;
      /** The ID of the swap generated by the provider */
      provider_swap_id: string;
    };
    export type RequestBody = never;
    export type RequestHeaders = {};
    export type ResponseBody = SwapDTO;
  }
  /**
   * @description Fetches the price(s) of the given currency/currencies in USD. Provide multiple currency IDs separated by commas.
   * @tags Price Feeder
   * @name PriceFeederControllerGetPrices
   * @request GET:/api/price-feeder
   */
  export namespace PriceFeederControllerGetPrices {
    export type RequestParams = {};
    export type RequestQuery = {
      /**
       * Comma-separated list of currency symbols to fetch its prices
       * @example "BTC,ETH,USDC"
       */
      currencies: string;
    };
    export type RequestBody = never;
    export type RequestHeaders = {};
    export type ResponseBody = CoinPriceDto[];
  }
  /**
   * @description Returns the list of the tokens supported by the API
   * @tags Tokens
   * @name TokensControllerGetTokens
   * @request GET:/api/tokens
   */
  export namespace TokensControllerGetTokens {
    export type RequestParams = {};
    export type RequestQuery = {};
    export type RequestBody = never;
    export type RequestHeaders = {};
    export type ResponseBody = TokenDTO[];
  }
  /**
   * @description Find a token by its symbol
   * @tags Tokens
   * @name TokensControllerGetToken
   * @request GET:/api/tokens/{symbol}
   */
  export namespace TokensControllerGetToken {
    export type RequestParams = {
      symbol: string;
    };
    export type RequestQuery = {};
    export type RequestBody = never;
    export type RequestHeaders = {};
    export type ResponseBody = TokenDTO;
  }
}
