name: Rsk Swap SDK CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  validation:
    name: Code integrity validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24.14.1'
      - name: NPM Login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
      - name: Install dependencies
        run: npm ci && npm run build
      - name: Validate code format
        run: npm run lint:validation
      - name: Run unit tests
        run: npm run test
